# Use OpenJDK 17 as the base image
FROM openjdk:17-jdk-slim

# Add application JAR to the container
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

# Run the application
ENTRYPOINT ["java", "-jar", "/app.jar"]